services:
  web:
    image: nginx:latest # Using the default Nginx image with custom configuration.
    volumes:
      # Mount the application code for live updates
      - ./:/var/www
      # Mount the Nginx configuration file
      - ./client/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      # Map port 80 inside the container to port 8080 on the host machine  
      - "8080:80"
    environment:
      - NGINX_HOST=localhost
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:9501:9501"  # WebSocket - localhost
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - XDEBUG_MODE=coverage,debug

  redis:
    image: redis:7-alpine
    ports:
      - "127.0.0.1:6379:6379"  # Redis - localhost only
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  redis_data: