services:
  web:
    image: nginx:latest # Using the default Nginx image with custom configuration.
    volumes:
      # Mount the application code for live updates
      - ./:/var/www
      # Mount the Nginx configuration file
      - ./client/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      # Map port 80 inside the container to port 8080 on the host machine
      - "127.0.0.1:${CLIENT_PORT}:80"
    environment:
      - NGINX_HOST=localhost
      - TZ=America/Sao_Paulo
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "127.0.0.1:${WEB_SOCKET_PORT}:9501"  # WebSocket - localhost
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - XDEBUG_MODE=coverage,debug

  redis:
    image: redis:7-alpine
    tmpfs:
      - /data
    # volumes:
    #   - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru

volumes:
  redis_data: